# Generated by Django 4.1.13 on 2024-04-02 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_image_and_more'),
        ('account', '0003_alter_profile_photo'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='total_kcal',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='type',
        ),
        migrations.AddField(
            model_name='routine',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.profile'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='exercises',
            field=models.ManyToManyField(related_name='exercise_routine', to='exercises.exercise'),
        ),
    ]
