# Generated by Django 5.0.3 on 2024-04-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_image'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='exercises',
            field=models.ManyToManyField(related_name='exercise_routine', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
