# Generated by Django 5.0.3 on 2024-03-15 17:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, help_text="User's date of birth", null=True)),
                ('photo', models.ImageField(blank=True, help_text="User's avatar", upload_to='users/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('weight', models.SmallIntegerField(blank=True, help_text="User's current weight")),
                ('height', models.SmallIntegerField(blank=True, help_text="User's current height")),
                ('status', models.CharField(choices=[('AC', 'Active'), ('DS', 'Disable'), ('CA', 'Cancelled')], default='AC', help_text='Current status of the profile', max_length=10)),
                ('user', models.OneToOneField(help_text='The user linked to this profile', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
