# Generated by Django 5.0.3 on 2024-04-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
