# Generated by Django 4.1.13 on 2024-04-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_remove_routine_total_kcal_remove_routine_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('friday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_routine', to='routines.routine')),
                ('monday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_routine', to='routines.routine')),
                ('saturday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saturday_routine', to='routines.routine')),
                ('sunday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_routine', to='routines.routine')),
                ('thursday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_routine', to='routines.routine')),
                ('tuesday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_routine', to='routines.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wednesday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_routine', to='routines.routine')),
            ],
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
