# Generated by Django 4.1.13 on 2024-04-30 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_photo'),
        ('tracker', '0002_week_delete_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='user',
        ),
        migrations.AddField(
            model_name='week',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='week_number',
            field=models.IntegerField(null=True),
        ),
    ]
