# Generated by Django 4.1.13 on 2024-04-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_week_user_week_profile_week_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='friday_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='monday_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='sunday_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='thursday_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='tuesday_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='wednesday_date',
            field=models.DateField(null=True),
        ),
    ]
