# Generated by Django 5.0.3 on 2024-03-15 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the exercise', max_length=255)),
                ('type', models.CharField(choices=[('LEG', 'Leg'), ('BI', 'Biceps'), ('TRI', 'Triceps'), ('CHE', 'Chest'), ('BA', 'Back'), ('SHO', 'Shoulders')], help_text='The muscle the exercise will work on', max_length=10)),
                ('description', models.TextField(help_text='Description how to do the exercise')),
                ('kcal', models.IntegerField(help_text='The number of kcals burnt per repetition')),
                ('required_material', models.CharField(help_text='Material you need to do the exercise', max_length=255)),
                ('image', models.ImageField(blank=True, help_text="Exercise's ilustration", upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
        ),
    ]
