# Generated by Django 4.1.13 on 2024-04-02 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, help_text="Exercise's ilustration", upload_to='exercise_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='required_material',
            field=models.CharField(choices=[('Barbell', 'Barbell'), ('Weight Plates', 'Weight Plates'), ('Dumbbells', 'Dumbbells'), ('Cable Machine', 'Cable Machine'), ('Bosu Ball', 'Bosu Ball'), ('Kettlebells', 'Kettlebells'), ('TRX', 'Trx')], help_text='Material you need to do the exercise', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Leg', 'Leg'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders')], help_text='The muscle the exercise will work on', max_length=10),
        ),
    ]
